### ISSUE TITLE
Lazarus on Ubuntu 14.04 64

### ISSUE THREAD

**Issue by OsvaldoTCF** [jmpessoa/lazandroidmodulewizard#1]
Collect data for use in the lamw on Lazarus 1.4 and FPC 3.0.1 installed on Ubuntu 04.14 64-bit .

**Comment by OsvaldoTCF** [comment]
_Get Android SDK e NDK.
_Download sdk packages for version 4.1.2
_Create a simbolic link (ln -s) to your sdk/ndk folder (/Android -> /your/folder/ (ndk and sdk))
_Add to your ~/.bashrc:
export PATH=$PATH:/Android/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin
_Download with svn
svn co http://svn.freepascal.org/svn/lazarus/branches/fixes_1_4/
svn co http://svn.freepascal.org/svn/fpc/branches/fixes_3_0/
_Compile and Install (on fixes_3_0)
make clean crossall OS_TARGET=android CPU_TARGET=arm
sudo make crossinstall OS_TARGET=android CPU_TARGET=arm
_create simbolic link:
cd /usr/local/bin
sudo ln -s /usr/local/lib/fpc/3.0.1/ppcrossarm .
sudo ln -s /Android/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-as arm-android-as
sudo ln -s /Android/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ld arm-android-ld
_Add lines below to /etc/fpc.cfg
#IFDEF ANDROID
#IFDEF CPUARM
-Fu/usr/local/lib/fpc/$fpcversion/units/$fpctarget
-Fu/usr/local/lib/fpc/$fpcversion/units/$fpctarget/*
-Fu/usr/local/lib/fpc/$fpcversion/units/$fpctarget/rtl
#ENDIF
#ENDIF
_ Install packages on Lazarus
_ After create projects change lines on Menu/Project/Project Options/ Paths and Other. The lines must reflect the folders, replace x86 for x86_64.

**Comment by OsvaldoTCF** [comment]
On file install.sh, on second line, clear slash from /bin
Ex: /Android/sdk/platform-tools/adb install -r /bin/an1-debug.apk
>>> /Android/sdk/platform-tools/adb install -r bin/an1-debug.apk

**Comment by leledumbo** [comment]
Unclear what you ask, please write the question. If it doesn't work, please tell what the compiler outputs.

**Comment by OsvaldoTCF** [comment]
Please, see this: https://github.com/jmpessoa/lazandroidmodulewizard/issues/2 (That's the problem)

This issue here was to record how am installing to provide support to some other users .

**Comment by OsvaldoTCF** [comment]
New version, a clean installation, all ok!
