### ISSUE TITLE
jsearchview missing features

### ISSUE THREAD

**Issue by jjhofman** [jmpessoa/lazandroidmodulewizard#106]
I am writing an android app for warehouse management purposes. The app is used on handterminals like the zebra mc3300 for scanning barcodes.
At this moment i am using the jtextedit component to search in the masterdata (the search can be initiated by a barcode scan).  The jsearchview component would be the most appropriate component to use because of the [x clear]  button. But it is not useable because of some missing features wich do exist in the jtextedit component:  

setfocus
selectall
hint

Is it possible to implement these features in the jsearchview?

**Comment by jmpessoa** [comment]
Done!

Added property:
Hint

Added methods:
SelectAll();
SelectAll(_highlightColor)
SetFocus();
ClearFocus();
SetIconified(boolean);

Thank you!

**Comment by jjhofman** [comment]
i cannot find these methods in the current download?
Also other improvements are gone...   
Looks like if an old release is now active

**Comment by jmpessoa** [comment]
Strange, maybe you're missing some sync ..... 

"Also other improvements are gone..."  Whats?

**Comment by jjhofman** [comment]
i did not re-install all packages 

but its working fine now, thank you very much
