### ISSUE TITLE
unzipper crash

### ISSUE THREAD

**Issue by jjhofman** [jmpessoa/lazandroidmodulewizard#108]
in my LAMW project I am trying to use the TUnzipper library to extract a file I downloaded to the dirdownloads.   (On my old WinCE project I use this same methodology to download a zipfile wich includes a SQLite Database file from a server.)

But even when i only use a simple textfile in the zipped archive, after tunzipper.extractallfiles() the application crashes.  The example textfile has been extracted to dirdownloads before the crash. 

Perhaps someone recognizes this and has a suggestion?

**Comment by jmpessoa** [comment]
Have you implemented the "runtime permissions"  to read/write  the file?

**Comment by jjhofman** [comment]
yes and also the permission for 'INTERNET'

1: first I download a small ini file to the downloads folder via tfphttpclient.get   [ok]
2: then i read this ini file for version information [ok]
3: download the masterdata zip file to downloads folder via tfphttpclient.get [ok]
4: extract contents of this zip file via tunzipper:  crashes after first file is extracted to downloads folder, this also happens when you put only a simple text file in the zipfile.

**Comment by JanuszChmiel** [comment]
If I can kindly give you A piece of advice, try to analyse logcat output 
for AN exact native crash related to using native code if this message 
is presented inside protocol or not.

**Comment by jjhofman** [comment]
could this be the cause of the crash?  Cause: seccomp prevented call to disallowed arm system call 269

07-13 10:58:29.574 28761 28761 F libc    : Fatal signal 31 (SIGSYS), code 1 (SYS_SECCOMP) in tid 28761 (konnektmobilev2), pid 28761 (konnektmobilev2)
07-13 10:58:29.696 29011 29011 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-13 10:58:29.697 29011 29011 F DEBUG   : Build fingerprint: 'HUAWEI/EML-L29/HWEML:9/HUAWEIEML-L29/293C432:user/release-keys'
07-13 10:58:29.697 29011 29011 F DEBUG   : Revision: '0'
07-13 10:58:29.697 29011 29011 F DEBUG   : ABI: 'arm'
07-13 10:58:29.697 29011 29011 F DEBUG   : pid: 28761, tid: 28761, name: konnektmobilev2  >>> org.intensus.konnektmobilev2 <<<
07-13 10:58:29.697 29011 29011 F DEBUG   : signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
07-13 10:58:29.697 29011 29011 F DEBUG   : Cause: seccomp prevented call to disallowed arm system call 269
07-13 10:58:29.697 29011 29011 F DEBUG   :     r0  ece8afac  r1  ffc657b0  r2  ffc657b0  r3  ece8afac
07-13 10:58:29.697 29011 29011 F DEBUG   :     r4  00000000  r5  5cd8633e  r6  c9797100  r7  0000010d
07-13 10:58:29.697 29011 29011 F DEBUG   :     r8  00000000  r9  eb943000  r10 ffc65d20  r11 ffc6591c
07-13 10:58:29.697 29011 29011 F DEBUG   :     ip  0012a1ac  sp  ffc657ac  lr  c96d0710  pc  c9662b34
07-13 10:58:29.699 29011 29011 F DEBUG   :
07-13 10:58:29.699 29011 29011 F DEBUG   : backtrace:
07-13 10:58:29.699 29011 29011 F DEBUG   :     #00 pc 00039b34  /data/app/org.intensus.konnektmobilev2-H6CpE8brxdoLUMZa3FNc5A==/lib/arm/libcontrols.so

**Comment by jjhofman** [comment]
I managed to get it to work by not unzipping the file(s) to a file but extracting it to a memorystream and then save it to a file. Below code works fine. So this might be usefull to others.

procedure TAndroidModule1.DoDoneOutZipStream(Sender: TObject; var AStream: TStream;
AItem: TFullZipFileEntry);
begin
AStream.Position:=0;
tmemorystream(astream).SaveToFile(androidmodule1.GetEnvironmentDirectoryPath(dirdownloads)+'/'+aitem.DiskFileName);
Astream.Free;
end;

**Comment by jmpessoa** [comment]
Great!

Can you, please,  make a simple App? So, we can post it in  LAMW "demos"

**Comment by jjhofman** [comment]
Here is the demo application for unzipping files 

[AppLamwUnzipDemo.zip](https://github.com/jmpessoa/lazandroidmodulewizard/files/3416171/AppLamwUnzipDemo.zip)

**Comment by jmpessoa** [comment]
Added to LAMW demos!!!
Thank you!
