### ISSUE TITLE
Designer

### ISSUE THREAD

**Issue by odisey1245** [jmpessoa/lazandroidmodulewizard#11]
I'm going to change default color of jForm to (R:240,G:240,B:240), that is default for Android 4.2.2 (api17). Why it is black? Draft classes should be also reworked for white background drawing.
Any objections?

**Comment by jmpessoa** [comment]
objections? no, nothing!

**Comment by odisey1245** [comment]
I just want to understand, why the black color was chosen.

**Comment by elera** [comment]
Good idea.

**Comment by jmpessoa** [comment]
Just because in early days almost all android  App had black background! :)))
