### ISSUE TITLE
jForm fixed size

### ISSUE THREAD

**Issue by odisey1245** [jmpessoa/lazandroidmodulewizard#15]
Why the size of jForm is fixed (hardcoded as 300x600, see androidwidget.pas:1819-1823)?

**Comment by jmpessoa** [comment]
There is not  a reason... just a experimental value to produce a sensation near of the real devices.

**Comment by odisey1245** [comment]
I'm going to drop this restriction and add appropriate component editor to change jForm size (predefined value list). Any objections?

**Comment by jmpessoa** [comment]
No... we can test this option!
