### ISSUE TITLE
Error while compiler AppJCenterOpenStreetMapDemo2 and others.

### ISSUE THREAD

**Issue by almir-lima** [jmpessoa/lazandroidmodulewizard#172]
Hi, Pessoa.
i have a trouble while compile some DEMO, 

attached log
[log.log](https://github.com/jmpessoa/lazandroidmodulewizard/files/3908267/log.log)
![Anotação 2019-12-01 105254](https://user-images.githubusercontent.com/58075693/69914981-c2f05880-1428-11ea-8901-64b156f3a1e6.jpg)

**Comment by jmpessoa** [comment]
Hi, iSoft!

Please,  update/fix  your Android SDK system.....
