### ISSUE TITLE
Error to create new project with last version.

### ISSUE THREAD

**Issue by almir-lima** [jmpessoa/lazandroidmodulewizard#177]
Hi me again.
In the latest GIT release, for a new Lazarus installation, an error occurs when the project is compiled by MENU -> "Run" -> [LAMW] Build Android Apk and Run

The CONTROLS.JAVA file is being created with a typo on lines number 1780 and 1785.

	//by TR3E
	public int GetScreenWidth() {
		return controls.appLayout..getWidth(); <--- double dot
	}                                ^

	//by TR3E
	public int GetScreenHeight() {
		return controls.appLayout..getHeight();  <--- double dot
	}                                 ^

The return of the function is being accessed from a double point instead of a single point.

I did the test correcting to a single point, and compiled from the command line, the APK was successfully generated in both ANT and GRADLE.

OBS:
With a old pack version of lazandroidmodulewizard, instaled in lazarus it's worked well, the APK was create with sucess.

**Comment by jmpessoa** [comment]
Fixed !!!!

Thank you!
