### ISSUE TITLE
Error in DEMO AppActionBarTabDemo1

### ISSUE THREAD

**Issue by almir-lima** [jmpessoa/lazandroidmodulewizard#178]
Hi Pessoa, i'm try compile the demo AppActionBarTabDemo1, but i get a error when i run the APP.
I'm attached the log from error.

Can i post the issues about compilation of the Demos here, or in the forum lazarus?

*** 

[ActionBarDemo1.txt](https://github.com/jmpessoa/lazandroidmodulewizard/files/3941178/ActionBarDemo1.txt)

**Comment by jmpessoa** [comment]
Yes, here is good. I will try some fix!

Thank you!

**Comment by jmpessoa** [comment]
Comment this line:
//jActionBarTab1.Add('ADDLIST', jPanel4.View{sheet view}, jPanel3.View {custom tab view!});

I will try fit it!

the param jPanel3.View {custom tab view!} has some problem...

**Comment by jmpessoa** [comment]
Ok. Fixed!  (but we lost custom tab view ... sorry.... )

**Comment by isoft-sistemas** [comment]
Very nice, it's worked!

**Comment by isoft-sistemas** [comment]
Hi, ActionBar Tab don't work with secondary Form.
The Demo work, but when is set in second form, ocurre an error.

I Attached the my demo and log of error.

[ActionBar.txt](https://github.com/jmpessoa/lazandroidmodulewizard/files/3946139/ActionBar.txt)

[jni.zip](https://github.com/jmpessoa/lazandroidmodulewizard/files/3946141/jni.zip)

**Comment by jmpessoa** [comment]
For "AppCompat"  material theme,  use only "Toolbar" 

[ActionBar is just for "old/legacy/test" projects....]

**Comment by isoft-sistemas** [comment]
OK, thanks

**Comment by jmpessoa** [comment]
"AppCompatNavigationDrawerDemo1"  is a good start point!

You can create a new  project and "import LAMW stuff" from demos!

**Comment by isoft-sistemas** [comment]
The Parent of component is automatically set when i put a component in the form or i must manually set?

**Comment by jmpessoa** [comment]
Yes, the visual/GUI  Parent is automatically set when you put the component in the form or others containers (jPanel,  jScrollView,  etc...)....  You can see in the Objector Inspector TreeList
