### ISSUE TITLE
Adjust to screen 4,5" and 6" (SOLVED)

### ISSUE THREAD

**Issue by almir-lima** [jmpessoa/lazandroidmodulewizard#186]
how adjust the screen, to show the buttons below?
In 6" the buttons are visible, but in 4,5" no.
i set the Panel to parentHeight=lpMatchParent.

![WhatsApp Image 2019-12-20 at 23 11 38](https://user-images.githubusercontent.com/58075693/71301479-5f4db100-237e-11ea-9d57-0d4d00c575a4.jpeg)
![android1](https://user-images.githubusercontent.com/58075693/71301487-6f659080-237e-11ea-9234-6b294a30f02c.jpeg)

**Comment by jmpessoa** [comment]
The concrete fact is [all] your information doesn't fit the into a tiny 4.5 screen! ... 

The solution is to put a jScroolView as your back/main container...  

Yes! you can do it without lose your good layout!

1) put a jScroolView at bottom of your main panel....

image 1: https://od.lk/f/Ml8xNzU4ODc2NDlf

2) close your project [or just the unit that will be edited....]

Open the unit ".lfm" file [notepad like editor]

copy the jScroolView data/config:

image 2: https://od.lk/f/Ml8xNzU4ODc3Njlf

paste it above your main jPanel... [and save!]

image 3: https://od.lk/f/Ml8xNzU4ODgxNTJf

NOTE: the  jScroolView  object "end"  [need be] stay below of the jPanel object "end"....

3) Re-Open your modified unit [or project...]

Set the  jScroolView properties:

    LayoutParamWidth = lpMatchParent
    LayoutParamHeight = lpMatchParent

image 4:  https://od.lk/f/Ml8xNzU4ODg2MTdf

Good Work!

**Comment by isoft-sistemas** [comment]
Hi, the data of customers are in the jScrollView , but the buttons are in the panel behind where o jScrollView. The idea is anchor the button below of jScrollView and allow tham the user can, click any moment, without need of scroll the layout. Exist a option where i can get the heigth of screen?

![image](https://user-images.githubusercontent.com/58075693/71359984-13149380-256d-11ea-990f-c1ad66d0b945.png)

**Comment by isoft-sistemas** [comment]
i adjusted the layout to screen 4,5", i go create a config file to work with variate height screen. thanks
