### ISSUE TITLE
jBluetoothClientSocket

### ISSUE THREAD

**Issue by euller88** [jmpessoa/lazandroidmodulewizard#19]
Here's the deal, I'm using the Bluetooth components in a demo application, which will serve as the foundation of a bigger application, which may turned into a commercial application in the future(who knows). Everything was OK, I was able enable the Bluetooth of the device, search for paired devices on the vicinity, and connect to one of the devices. But was after that where the problems started to begin.

First: the application was unable to disconnect from the other device using jBluetoothClientSocket.Disconnect(). I assured that a device should be connected before calling this method, and set the application to inform the user if connection was terminated. But after the call, the other device keep telling me that the connection was active, and due the nature of Bluetooth, this shouldn't be true if the method was successful.

Second:The other device didn't received data sent from the application using jBluetoothClientSocket.Write(), and the application was able to retrieve the data using jBluetoothClientSocket.Read either. And I also had ways to assure and measure if the other device had sent or received data.

I don't know if I'm misusing the components, but they seemed intuitive, so I worked with what I had. But I'm certainly misguided, because LAMW has little to no documentation, and that may had been the cause of these inconsistencies.

Thank you in advance for any help.

**Comment by jmpessoa** [comment]
Hi Euller!
Sorry, jBluetoothClientSocket and BluetoothServerSocket are not finished yet! As soon as possible I will try fix its...... at the moment only  jBluetooth is ok.

**Comment by euller88** [comment]
Well, since I have the need of these features, I'm gonna fork your project and try to implement them myself. Because, you have your own problems to deal, and would be asking too much of you to make this for me because I need it, and I'm too lazy to do. So wait a few days, and maybe some results will appear. Thanks for the excellent work you've done until now and keep it up.

**Comment by euller88** [comment]
In my excitement to help, I forgot something: I have no clue on how to begin. I know how to make a new component, because I read the tutorial, but I have no idea on how to change the existing ones. So how do I begin to do it?

**Comment by euller88** [comment]
Well, I tried to do by myself, and failed miserably. I don't know the why, I used code that worked on other application and nothing. Every time I tested the new component with the modified functionalities, the application didn't even start properly. For now, I'm gonna put this on pause, but I will return to it briefly.

**Comment by jmpessoa** [comment]
Ok, I also had to do this to avoid delaying the project ...  but I will return in the weekend ...let's see what I can do

**Comment by OsvaldoTCF** [comment]
Very well, José.
Thank you.

2015-06-11 20:03 GMT-03:00 Jose Marques Pessoa <notifications@github.com>:

> Ok, I also had to do this to avoid delaying the project ... but I will
> return in the weekend ...let's see what I can do
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jmpessoa/lazandroidmodulewizard/issues/19#issuecomment-111301853>
> .
>



-- 
             - Osvaldo T Crispim Filho -
