### ISSUE TITLE
Hi, you can add a component for use UDP protocol?

### ISSUE THREAD

**Issue by almir-lima** [jmpessoa/lazandroidmodulewizard#191]
Hi Pessoa, you can add a component for use UDP protocol?
I have a specific job than need this protocol to consume some services.
Thanks

**Comment by jmpessoa** [comment]
Look for "jUDPSocket" component .... [Android Bridges Extra]
and the demo: "AppUDPSocketDemo1"

**Comment by almir-lima** [comment]
Sorry, i don't seeked the samples.
thanks for your response.
;-)
