### ISSUE TITLE
Lazarus on Ubuntu 14.04 64: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by OsvaldoTCF** [jmpessoa/lazandroidmodulewizard#2]
Some components are giving this issue: java.lang.NoClassDefFoundError

W/dalvikvm( 1714): JNI WARNING: JNI method called with exception pending
W/dalvikvm( 1714):              in Lorg/deskx/an1/Controls;.pAppOnCreate:(Landroid/content/Context;Landroid/widget/RelativeLayout;)V (NewGlobalRef)
W/dalvikvm( 1714): Pending exception is:
I/dalvikvm( 1714): java.lang.NoClassDefFoundError: org.deskx.an1.jPanel
I/dalvikvm( 1714):     at org.deskx.an1.Controls.jPanel_Create(Controls.java:10177)

**Comment by OsvaldoTCF** [comment]
This occurs with these components:
jPanel jBitmap jWebview jSqlite* jLocation jMediaPlayer jSpinner

**Comment by leledumbo** [comment]
Doesn't happen here. At least the SQLite demo works. Can you confirm that?

**Comment by OsvaldoTCF** [comment]
A clean installation with new version, all ok!
