### ISSUE TITLE
[Solved] Cannot Install Grandle Release APK (Corrupt)

### ISSUE THREAD

**Issue by tauhidcp** [jmpessoa/lazandroidmodulewizard#203]
I can't install the apk release from grandle but the apk debug work fine.

![lamwerror](https://user-images.githubusercontent.com/6273181/76137600-e9520f80-6079-11ea-92cd-b0ef04764472.jpg)

**Comment by tauhidcp** [comment]
solved. read **How_To_Get_Your_Signed_Release_Apk.txt** file

**Comment by jmpessoa** [comment]
Congratulations!!!
