### ISSUE TITLE
Compiling Error androidthemes.pas line 650

### ISSUE THREAD

**Issue by Coldzer0** [jmpessoa/lazandroidmodulewizard#204]
```
androidthemes.pas(650,28) Error: (3284) Operator is not overloaded: "Class Of TDOMElement" and "Boolean"
```

https://github.com/jmpessoa/lazandroidmodulewizard/blob/a6aad388c7cd7becd1b8729aaca9872deef0c59a/android_wizard/androidthemes.pas#L650

it should be

> if **(**n1 is TDOMElement**)** and TDOMElement(n1).hasAttribute(aname) then

**Comment by jmpessoa** [comment]
Fixed! 
Thank  you!

**Comment by Coldzer0** [comment]
Welcome and thanks for such great project
