### ISSUE TITLE
LAMW with JSON

### ISSUE THREAD

**Issue by euller88** [jmpessoa/lazandroidmodulewizard#23]
Hey guys, I think i discovered a bug in LAMW. Whenever I try to retrieve data from a JSON object, the application crashes, and I receive the following message from logcat:

```
A/libc(30743): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)
```

I can do almost anything with a JSON object, and the application goes on. But when I try to access the fields of my JSON objects, one of the most crucial things within the application, the crash happens.

I don't know the reason yet, but I think the problem may be general for all LAMW users. Because of that, I've made a smaller application that reproduces the error, here is the unit for it:

```pascal
unit testgui;

{$mode delphi}

interface

uses
  Classes, SysUtils, And_jni, And_jni_Bridge, Laz_And_Controls, 
    Laz_And_Controls_Events, AndroidWidget, fpjson, jsonparser, fpjsonrtti;

type

  TMyObj = class
    id:Integer;
    name:String;
    val:Real;
  end;

  { TAndroidModule1 }

  TAndroidModule1 = class(jForm)
    jButton1: jButton;
    jListView1: jListView;
    procedure jButton1Click(Sender: TObject);
  private
    {private declarations}
  public
    {public declarations}
  end;

const
  json = '[{"id":1,"name":"first","val":2.5},{"id":2,"name":"second","val":3.5},{"id":3,"name":"third","val":4.5}]';

var
  AndroidModule1: TAndroidModule1;

implementation

{$R *.lfm}

{ TAndroidModule1 }

procedure TAndroidModule1.jButton1Click(Sender: TObject);
var
  vja: TJSONArray;
  vjo: TJSONObject;
  vobj: TObject;
  vmyo: TMyObj;
  vdst: TJSONDeStreamer;
  i: Integer;
  s: String;
begin
  try
    try
      vdst:= TJSONDeStreamer.Create(nil);
      vdst.CaseInsensitive:= true;
      vmyo:= TMyObj.Create;
      vja:= TJSONArray(GetJSON(json));
      vjo:= vja.Objects[0];
      ShowMessage(vjo.AsJSON);
      ShowMessage('== If this is shown, then phase 1 is fine ==');
      vdst.JSONToObject(vjo,vobj);
      vmyo:= vobj as TMyObj;
      ShowMessage('== If this is shown, then phase 2 is fine ==');
    except

    end;
  finally

  end;
end;

end.
```

**Comment by OsvaldoTCF** [comment]
No problem with JSON.
Ok with this:

procedure TAndroidModule1.jButton1Click(Sender: TObject);
var
  vja: TJSONArray;
  i: Integer;
  s: String;
  VParser : TJSONParser;
begin
  i := jListView1.Count;
  try
    try
      vja := TJSONArray.Create;
      VParser := TJSONParser.Create(json);
      try
        vja := VParser.Parse as TJSONArray;
      finally
        VParser.free;
      end;

      s := vja.Objects[i].Get('name');
      ShowMessage('Nome: '+s);
      s := vja.Objects[i].Get('name')+' - '+
        floattostr(vja.Objects[i].Get('val'));
      ShowMessage(s);
      jListView1.Add(s);
      i := jListView1.Count;
      ShowMessage('Items: '+inttostr(i));
    except
       ShowMessage('Error');
    end;
  finally
    vja.Free;
  end;
end;

**Comment by OsvaldoTCF** [comment]
No problem with JSON.
Ok with this:
==========
procedure TAndroidModule1.jButton1Click(Sender: TObject);
var
  vja: TJSONArray;
  i: Integer;
  s: String;
  VParser : TJSONParser;
begin
  i := jListView1.Count;
  try
    try
      vja := TJSONArray.Create;

      VParser := TJSONParser.Create(json);
      try
        vja := VParser.Parse as TJSONArray;
      finally
        VParser.free;
      end;

      s := vja.Objects[i].Get('name');
      ShowMessage('Nome: '+s);

      s := vja.Objects[i].Get('name')+' - '+
        floattostr(vja.Objects[i].Get('val'));
      ShowMessage(s);

      jListView1.Add(s);
      i := jListView1.Count;
      ShowMessage('Items: '+inttostr(i));
    except
       ShowMessage('Error');
    end;
  finally
    vja.Free;
  end;
end;  
==========
