### ISSUE TITLE
Error in jImageBtn.java:107: error: cannot find symbol

### ISSUE THREAD

**Issue by almir-lima** [jmpessoa/lazandroidmodulewizard#232]
Hi Pessoa, i try compile a project with jImageBtn component and i receive this message,

Error in jImageBtn.java:107: error: cannot find symbol

if i remove its from my project, the project compile normal.

![image](https://user-images.githubusercontent.com/58075693/87346662-5560ea80-c528-11ea-8436-4a2e144d8ea0.png)

**Comment by jmpessoa** [comment]
Fixed and Improved jImageBtn!

Thanks!
