### ISSUE TITLE
lamwdesigner.pas Error: (4025) Incompatible type for arg

### ISSUE THREAD

**Issue by Coldzer0** [jmpessoa/lazandroidmodulewizard#316]
I updated my Lazarus IDE to the latest version in trunk and this error popped up
```log
E:\FPCross\ccr\lamw\android_wizard\lamwdesigner.pas(1771,68) Error: (4025) Incompatible type for arg no. 1: Got "<procedure variable type of procedure of object;Register>", expected "<procedure variable type of procedure(TPersistent) of object;Register>"
E:\FPCross\ccr\lamw\android_wizard\lamwdesigner.pas(1792,73) Error: (4025) Incompatible type for arg no. 1: Got "<procedure variable type of procedure of object;Register>", expected "<procedure variable type of procedure(TPersistent) of object;Register>"
```

I fixed it by changing in line

https://github.com/jmpessoa/lazandroidmodulewizard/blob/master/android_wizard/lamwdesigner.pas#L63
to

```pascal
procedure OnPersistentDeleted(APersistent: TPersistent);
```
and for sure for the implementation in line

https://github.com/jmpessoa/lazandroidmodulewizard/blob/master/android_wizard/lamwdesigner.pas#L1974
to

```pascal
procedure TAndroidWidgetMediator.OnPersistentDeleted(APersistent: TPersistent);
```

I'm not sure if this error is present in the stable version of the IDE or not so it's better to double check.

**Comment by jmpessoa** [comment]
Maybe a Lazarus issue, not a FPC  issue ...

Can you suggest some "IFDEF  version" compile directive?

**Comment by jmpessoa** [comment]
In line 1771 [lamwdesigner.pas] you can track until "PropEdit.pas" line 109  and see change....

So we need something like [as in lamwdesigner.pas line 61]:

procedure OnPersistentDeleted($IF lcl_fullversion=??????}APersistent: TPersistent{$ENDIF});

You can see the "fullversion"  in "LazVersion.pas"

In my system I have:
const
  laz_major = 2;
  laz_minor = 0;
  laz_release = 0;
  laz_patch = 4;
  laz_fullversion = ((laz_major *  100 + laz_minor) * 100 + laz_release) * 100 + laz_patch;
  laz_version = '2.0.0.4';

**Comment by Coldzer0** [comment]
> Maybe a Lazarus issue, not a FPC issue ...
> 
> Can you suggest some "IFDEF version" compile directive?

yes I meant the Lazarus IDE I fixed it.

2010000 = the trunk version 

I think something like this would work using the lcl_fullversion >= 2010000

So anything from 2.1.0 will work fine as long as no changes happen.

```pascal
procedure OnPersistentDeleted({$if lcl_fullversion>=2010000}APersistent: TPersistent{$endif});
```
```pascal
procedure TAndroidWidgetMediator.OnPersistentDeleted({$if lcl_fullversion>=2010000}APersistent: TPersistent{$endif});
```

I Tested it on trunk version and works fine, But I didn't test on a stable version.

**Comment by jmpessoa** [comment]
I will apply your suggestion!!

Thank you!

**Comment by Iwoks** [comment]
Hello,

FPC : 3.3.1 / LAZ  : 2.1.0 - Trunk

  A few weeks ago I had done a LAMW installation from the trunk branch with FPCupDeluxe, without any problems. 
  Yesterday, I needed to do a new installation, and i have this same message.

```
C:\fpcupdeluxe\laz\ccr\lamw\android_wizard\lamwdesigner.pas(1772,68) Error: (4025) Incompatible type for arg no. 1: Got "<procedure variable type of procedure of object;Register>", expected "<procedure variable type of procedure(TPersistent) of object;Register>"
C:\fpcupdeluxe\laz\ccr\lamw\android_wizard\lamwdesigner.pas(1793,73) Error: (4025) Incompatible type for arg no. 1: Got "<procedure variable type of procedure of object;Register>", expected "<procedure variable type of procedure(TPersistent) of object;Register>"
```

  I had to fix this problem by re-inverting comments.

```
    procedure OnPersistentDeleted;
    //procedure OnPersistentDeleted({$if lcl_fullversion>2010000}APersistent: TPersistent{$endif}); //thanks to @Coldzer0 !

    procedure TAndroidWidgetMediator.OnPersistentDeleted(APersistent: TPersistent);
   //procedure TAndroidWidgetMediator.OnPersistentDeleted({$if lcl_fullversion>2010000}APersistent: TPersistent{$endif});


```

**Comment by jmpessoa** [comment]
Maybe we nee put this issue in Lazarus [oficial] Forum....
