### ISSUE TITLE
Error direct load image to jimageview not from uri object

### ISSUE THREAD

**Issue by jokokiswan** [jmpessoa/lazandroidmodulewizard#323]
any solution? (android 10)

**Comment by jmpessoa** [comment]
Please,  put here your "loading" code.... from where you need load?

**Comment by jokokiswan** [comment]
I build app using api 29, your camera2 sample not worked, taking picture from camera worked, but open it on jimageview failed on android10, but works well on andtoid8 :)

**Comment by jokokiswan** [comment]
1 more, request creating jftp delete file :) mftp.deleteFiles(_remote)

**Comment by jmpessoa** [comment]
Please, put your code here.... 

(that work in Android8 but fail for Android10....)

**Comment by jokokiswan** [comment]
it embarrasses me :) forgot giving permission before open.

**Comment by jokokiswan** [comment]
{Hint: save all files to location: C:\adt32\eclipse\workspace\AppIntentDemo1\jni }
unit unit1;

{$mode delphi}

interface

uses
  Classes, SysUtils, And_jni, And_jni_Bridge, Laz_And_Controls, Laz_And_Controls_Events,
  AndroidWidget, intentmanager, imagefilemanager;

type

  { TAndroidModule1 }

  TAndroidModule1 = class(jForm)
    jButton1: jButton;
    jButton2: jButton;
    jButton3: jButton;
    jCamera1: jCamera;
    jImageFileManager1: jImageFileManager;
    jImageView1: jImageView;
    jIntentManager1: jIntentManager;
    jTextView1: jTextView;
    jTimer1: jTimer;
    procedure AndroidModule1ActivityResult(Sender: TObject;
      requestCode: integer; resultCode: TAndroidResult; intentData: jObject);
    procedure jButton1Click(Sender: TObject);
    procedure jButton2Click(Sender: TObject);
    procedure jButton3Click(Sender: TObject);
    procedure jTimer1Timer(Sender: TObject);
  private
    {private declarations}
  public
    {public declarations}
  end;

var
  AndroidModule1: TAndroidModule1;

implementation

{$R *.lfm}

{ TAndroidModule1 }

procedure TAndroidModule1.jButton1Click(Sender: TObject);
begin
  //ref http://developer.android.com/reference/android/content/Intent.html
  //android.intent.action.VIEW
  //android.intent.action.PICK
  //android.intent.action.SENDTO
  //android.intent.action.EDIT
  //android.intent.action.DIAL
  //android.intent.action.CALL_BUTTON

  jIntentManager1.SetAction('android.intent.action.PICK');
  //or jIntentManager1.IntentAction:= iaPick;

  jIntentManager1.SetMimeType('image/*');
  //or 'image/png' etc..  mime here must be lowercase!
  jIntentManager1.StartActivityForResult(1001);      //user-defined requestCode=1001
end;

procedure TAndroidModule1.jButton2Click(Sender: TObject);
begin
  if IsRuntimePermissionGranted('android.permission.CAMERA') and
    IsRuntimePermissionGranted('android.permission.WRITE_EXTERNAL_STORAGE') then
  begin
    jcamera1.RequestCode:=2001;
    jcamera1.TakePhoto;
{
  //------------------------------------------------------
  if self.FileExists(androidModule1.GetEnvironmentDirectoryPath(dirDCIM) +
    '/photo1.jpg') then
  begin
    ShowMessage('ada');
    if IsRuntimePermissionGranted('android.permission.WRITE_EXTERNAL_STORAGE') then
    begin
      //ShowMessage(gApp.path.DCIM + '/photo1.jpg');
      jImageView1.SetImageBitmap(jImageFileManager1.LoadFromFile(
        gApp.path.DCIM, 'photo1.jpg'));
    end;
    //self.CopyFile(androidModule1.GetEnvironmentDirectoryPath(dirDCIM) + '/photo1.jpg',androidModule1.GetEnvironmentDirectoryPath(dircache) + '/photo1.jpg');
    //jbitmap1.LoadFromFile(androidModule1.GetEnvironmentDirectoryPath(dirDCIM) +
    //  '/photo1.jpg');
    //jImageView1.SetImageBitmap(jImageFileManager1.LoadFromFile(
    //  androidModule1.GetEnvironmentDirectoryPath(dirDCIM) + '/photo1.jpg'));

  end
  else
    ShowMessage('gak ada');
  exit;
  }
  end;
end;

procedure TAndroidModule1.jButton3Click(Sender: TObject);
begin
  //------------------------------------------------------
  if self.FileExists(androidModule1.GetEnvironmentDirectoryPath(dirDCIM) +
    '/photo1.jpg') then
  begin
    ShowMessage('ada');
    if IsRuntimePermissionGranted('android.permission.WRITE_EXTERNAL_STORAGE') then
    begin
      //ShowMessage(gApp.path.DCIM + '/photo1.jpg');
      jImageView1.SetImageBitmap(jImageFileManager1.LoadFromFile(
        gApp.path.DCIM, 'photo1.jpg'));
    end;
    //self.CopyFile(androidModule1.GetEnvironmentDirectoryPath(dirDCIM) + '/photo1.jpg',androidModule1.GetEnvironmentDirectoryPath(dircache) + '/photo1.jpg');
    //jbitmap1.LoadFromFile(androidModule1.GetEnvironmentDirectoryPath(dirDCIM) +
    //  '/photo1.jpg');
    //jImageView1.SetImageBitmap(jImageFileManager1.LoadFromFile(
    //  androidModule1.GetEnvironmentDirectoryPath(dirDCIM) + '/photo1.jpg'));

  end
  else
    ShowMessage('gak ada');
  exit;

end;

procedure TAndroidModule1.jTimer1Timer(Sender: TObject);
begin
  if IsRuntimePermissionGranted('android.permission.WRITE_EXTERNAL_STORAGE') then
  begin
    //ShowMessage(gApp.path.DCIM + '/photo1.jpg');
    jImageView1.SetImageBitmap(jImageFileManager1.LoadFromFile(
      gApp.path.DCIM, 'photo1.jpg'));
  end;
  jTimer1.Enabled:=false;
end;

procedure TAndroidModule1.AndroidModule1ActivityResult(Sender: TObject;
  requestCode: integer; resultCode: TAndroidResult; intentData: jObject);
var
  jUri: jObject;
begin
  if requestCode = 1001 then  //user-defined requestCode=1001
  begin
    if resultCode = RESULT_OK then  //ok
    begin
      jUri := jIntentManager1.GetDataUri(intentData);
      jImageView1.SetImageBitmap(jImageFileManager1.LoadFromUri(jUri));
      //curiosity: You can try this ....
      //jImageView1.SetImageBitmap(jImageFileManager1.AnticlockWise(jImageFileManager1.LoadFromUri(jUri),jImageView1.jSelf));
    end
    else
      ShowMessage('Fail/cancel to pick a image ....');
  end;
  if requestCode = 2001 then  //user-defined requestCode=1001
  if resultCode = RESULT_OK then
    //ShowMessage(gApp.path.DCIM + '/photo1.jpg');
    jImageView1.SetImageBitmap(jImageFileManager1.LoadFromFile(
      gApp.path.DCIM, 'photo1.jpg'));
end;

end.  

if add support library checked, it would fail. 
![Capture](https://user-images.githubusercontent.com/58895576/107134969-64c2dd80-6929-11eb-8323-71d37a89ea9f.PNG)

i tried making new project using jcamera, giving permission, it always failed wether checking support library or not, sdk 29, android 10

**Comment by jokokiswan** [comment]
work like a charm,
replacing res/xml/support_provider_path.xml with this:

<?xml version="1.0" encoding="utf-8"?>
<paths>
  <external-path
    name="external"
    path="." />
  <external-files-path
    name="external_files"
    path="." />
  <cache-path
    name="cache"
    path="." />
  <external-cache-path
    name="external_cache"
    path="." />
<files-path
    name="files"
    path="." />
</paths>
