### ISSUE TITLE
jAsyncTask Error

### ISSUE THREAD

**Issue by Nenirey** [jmpessoa/lazandroidmodulewizard#353]
Hi jmpessoa, i found an error with the jAsyncTask and is not working:
java.lang.NoSuchMethodError: no non-static method "Lcu/segator/databubble/Controls;.jAsyncTask_Create(J)Ljava/lang/Object;"

this happen with the AsyncDemo1 too

**Comment by Nenirey** [comment]
the jAsyncTask_Create was an error in my lam (the Controls.java in my src app folder is not up to date) but the real problem is this:
JNI DETECTED ERROR IN APPLICATION: thread Thread[1,tid=2134,Native,Thread*=0xb0f85400,peer=0x742f2550,"main"] using JNIEnv* from thread Thread

**Comment by jmpessoa** [comment]
Hi,  

I will try some solution... but   jAsyncTask is very problematic ...

If you need  some async task, the better is to improve the java template
for  that specific method component ...
