### ISSUE TITLE
LAMW New project wizard missing NDK API levels

### ISSUE THREAD

**Issue by WayneSherman** [jmpessoa/lazandroidmodulewizard#383]
For ARM, the NDK has folders from 16 to 30 (missing 20, 25)
$HOME/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/

For AArch64, the NDK has folders from 21 to 30 (missing 25)
$HOME/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/

But the LAMW new project wizard lists NDK API levels:  16, 17, 18, 19, 21, 22, 23, 24, 26

**The new project wizard is missing NDK API levels 27, 28, 29, 30.**

Test environment:
Xubuntu 20.04 64-bit
installed using FPCUPdeluxe ver 1.8.2u
FPC stable v3.2.2
Lazarus stable v2.0.12
LAMW git from 2021-Jun-05

Android Command-Line Tools build 7302050
OpenJDK 11
Android SDK/API Level 29 (Android 10)
Android NDK revision 22
Gradle 6.8.3 (installed automatically by FPCUPdeluxe)

64-bit CPU Target: Aarch64
Target SDK 29

Forum Reference:
https://forum.lazarus.freepascal.org/index.php/topic,54878.msg408047.html#msg408047

**Comment by LongDirtyAnimAlf** [comment]
Thanks. NDK R22 has changed many things. The whole platform structure is not there anymore. This needs a lot of changes.
I would advice to stick with a LTS R21 for the time being.

**Comment by WayneSherman** [comment]
> NDK R22 has changed many things.
Aside from some LAMW UI issues, it does seem to generally work for building the few simple apps I tested (I had to edit LAMW.ini to set the settings).  I will test R21 and report back.

**Comment by WayneSherman** [comment]
Tested with NDK rev 21.4.7075529 with same issue.  New project wizard is missing 27, 28, 29 and 30 NDK API levels.

For screenshot see:
https://forum.lazarus.freepascal.org/index.php/topic,54878.msg408374.html#msg408374

**Comment by LongDirtyAnimAlf** [comment]
> New project wizard is missing 27, 28, 29 and 30 NDK API levels.

This is on purpose by the original author of LAMW.

**Comment by jmpessoa** [comment]
Hi!

About "New project wizard is missing 27, 28, 29 and 30 NDK API levels."....

I will fix it! But remember if you set NDK Api > 22 your project will not run in  Android 4.xxxx [and maybe 5.xxx] old devices....

**Comment by WayneSherman** [comment]
I tested this on Linux.  It is fixed.

Reference commit:  #https://github.com/jmpessoa/lazandroidmodulewizard/commit/f1d36f77acd2f00661dd5a7f761771e891e228fe
