### ISSUE TITLE
Compile error..

### ISSUE THREAD

**Issue by FezaCakir** [jmpessoa/lazandroidmodulewizard#388]
uFormBuildFPCCross.pas(370,13) Error: Identifier idents no member "Scanners"

Lazarus 2.3.0 r65258 FPC 3.3.1 x86_64-linux-gtk2

**Comment by jmpessoa** [comment]
Symbol "Scanners" was deprecated  and now we need replace it by " Parser"  .....

**Comment by jmpessoa** [comment]
Well, there is some code to handle this issue....

here in line 371:   (uFormBuildFPCCross.pas.pas)

       {$IF LCL_FULLVERSION >= 2010000}
       Tool.Parsers.Add(SubToolDefault);
       {$ELSE}
       Tool.Scanners.Add(SubToolDefault);
       {$ENDIF}

Why does this code fail?

**Comment by FezaCakir** [comment]
> Parser

I'll try as soon as possible..

**Comment by FezaCakir** [comment]
> Symbol "Scanners" was deprecated and now we need replace it by " Parser" .....

I will try as soon as possible.
Thanks..

**Comment by FezaCakir** [comment]
It's passed. But there is new error that is
amw_ide_menu_items.pas(38,5) Error: Identifier not found "FpChmod"

**Comment by FezaCakir** [comment]
procedure SaveShellScript(script: TStringList; const AFileName: string);
begin
    script.SaveToFile(AFileName);
    {$ifdef Unix}
    FpChmod(AFileName, &751);
    {$endif}
end;

**Comment by FezaCakir** [comment]
amw_ide_menu_items.pas(1414,11) Error: Identifier not found "hProcAProcessess"

**Comment by FezaCakir** [comment]
Done!

**Comment by jmpessoa** [comment]
Congratulations!!!!

**Comment by FezaCakir** [comment]
AndroidManifest.xml is always have wrong variables and values.
I guess, LAMW is not work correct. It seems better work with Android Studio.

**Comment by FezaCakir** [comment]
In 'file:///home/......./AndroidManifest.xml' (line 3 pos 87): Expected whitespace.

Press OK to ignore and risk data corruption.
Press Abort to kill the program.

<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" package="xxx.xxx.PROJECTFILENAME" android:versionCode="1" android:versionName="1.0">
  <uses-sdk android:minSdkVersion="23" android:targetSdkVandroid:targetSdkVersion="29"n android:name="android.permission.INTERNET"/>
  <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:anyDensity="true"/>
  <application android:usesCleartextTraffic="true" android:allowBackup="true" android:icon="@drawable/ic_launcher" android:label="@string/app_name" android:theme="@style/AppTheme">
    <activity android:name="PROJECTFILENAME" android:label="@string/app_name" android:configChanges="orientation|keyboardHidden|screenSize|screenLayout|fontScale" android:launchMode="standard" android:enabled="true">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>
  </application>
</manifest>

**Comment by jmpessoa** [comment]
"I guess, LAMW is not work correct........"

You can "guess"  but I can only try fix some "real"  bug.....

Please, 

just create a new project..... (don't compile it....!!!!!)

Zip it and send to:  jmpessoa@hotmail.com

**Comment by FezaCakir** [comment]
I have just sent an email that includes project files.
Regards.

**Comment by jmpessoa** [comment]
Ok.

The  project error is here in manifest..... a terrible mess in this line:

<uses-sdk android:minSdkVersion="dummySdkApi" a14tSdkVersion="dummyTargetApi"/30rmission android:name="android.permission.NFC"/>

Why????

1) Maybe you "androidmanifest.txt"  template in LAMW folder "......\android_wizard\smartdesigner\java"   is messy/dirty !!!!  

You can get the original from here:

https://github.com/jmpessoa/lazandroidmodulewizard/blob/master/android_wizard/smartdesigner/java/androidmanifest.txt

and replace the one damaged in  LAMW folder "......\android_wizard\smartdesigner\java" 

2) or you LAMW is damaged  ??? (Please, re-install  LAMW !!!)

**Comment by FezaCakir** [comment]
All option has done but there is still issue on AndroidManifest.xml

**Comment by FezaCakir** [comment]
Hi there.
I installed Laz4Android, Android SDK+NDK into Windows 7 x64. There is no issue. 
But, in Linux, problem is going on.
Thanks.
