### ISSUE TITLE
jListView Filter

### ISSUE THREAD

**Issue by JKennes** [jmpessoa/lazandroidmodulewizard#399]
orig_alist is not cleared:
After filling a jListView and applying a filter, the orig_alist gets filled with the contents of alist.
After clearing and filling the same jListView with other items the following happens when pressing the X button in the search box, without first applying a new filter: The alist gets filled with the items from the previous list, which are still present in the orig_alist.

I suggest to clear the orig_alist together with the alist in "public void Clear()".
Alose the orig_alist doesn't get cleaned up in "public void Free()"

**Comment by jmpessoa** [comment]
Done!    

if you notice any "new" unwanted behavior after the change, please notify us here! 

Thank you!

**Comment by JKennes** [comment]
Thank you for referencing me in your code, but could you please use my correct name @JKennes (instead of @jKannes)

I had problems using jHttpClient.Post. 
On examening the code in "Laz_And_Controls.pas", I found on rule 7789 it was calling 'GetStateFul' instead of 'Post'

I also got an error when releasing/freeing the jHttpClient object. I got something like 'method Free() does not exist'.
I solved this by adding this procedure to "jHttpClient.java" ( I added it after 'jFree()' )
```
    public  void Free() {
        jFree();
    }
```

**Comment by jmpessoa** [comment]
Done!

Thank you!
