### ISSUE TITLE
Set LAMW Directive

### ISSUE THREAD

**Issue by chacalfloripa** [jmpessoa/lazandroidmodulewizard#485]
is there any directive that identifies that we are compiling a LAMW project?
This directive is important for using shared codes that use LCL.

**Comment by jmpessoa** [comment]
you can try 

{$IFDEF android}
  //my FCL units or code....
{$ENDIF}

**Comment by jmpessoa** [comment]
well, maybe you will need  this....

{$IFNOTDEF android}
//my FCL units or code....
{$ENDIF}

**Comment by chacalfloripa** [comment]
okay, that works.
{$IFDEF android}
    {$IFDEF FMX}
         // FMX code or unit.
   {$ELSE}
         // FCP code or unit 
   {$ENDIF}
{$ENDIF}
