### ISSUE TITLE
checkDebugDuplicateClasses

### ISSUE THREAD

**Issue by marcos-ebm** [jmpessoa/lazandroidmodulewizard#506]
When placing the jBarcodeGen and ZXingBarcodeScan components in the form, a lot of errors appear 'checkDebugDuplicateClasses' (image below)

The solution I found was to comment a line in build.gradle (image below), but I think it's not the right way, as other components may need it
```
dependencies {
    //implementation  fileTree(include: ['*.jar'], dir: 'libs')
```

![Captura de Tela 2024-01-19 às 17 46 22](https://github.com/jmpessoa/lazandroidmodulewizard/assets/77758127/c22a13a7-f199-42f6-b92f-f2c40efa44f2)
![Captura de Tela 2024-01-19 às 18 47 20](https://github.com/jmpessoa/lazandroidmodulewizard/assets/77758127/7c9702b6-1837-4a5a-8b15-3d10b597a02a)

**Comment by jmpessoa** [comment]
Olá, Marcos!

Tente cada componente separadamente.....  e me informe se funciona.....

(o fato é que os dois componentes utilizam as mesmas bibliotecas com versões diferentes...)
________________________________
From: marcos-ebm ***@***.***>
Sent: Friday, January 19, 2024 5:51 PM
To: jmpessoa/lazandroidmodulewizard ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jmpessoa/lazandroidmodulewizard] checkDebugDuplicateClasses (Issue #506)


When placing the jBarcodeGen and ZXingBarcodeScan components in the form, a lot of errors appear 'checkDebugDuplicateClasses' (image below)

The solution I found was to comment a line in build.gradle (image below), but I think it's not the right way, as other components may need it

dependencies {
    //implementation  fileTree(include: ['*.jar'], dir: 'libs')


Captura.de.Tela.2024-01-19.as.17.46.22.png (view on web)<https://github.com/jmpessoa/lazandroidmodulewizard/assets/77758127/c22a13a7-f199-42f6-b92f-f2c40efa44f2>
Captura.de.Tela.2024-01-19.as.18.47.20.png (view on web)<https://github.com/jmpessoa/lazandroidmodulewizard/assets/77758127/7c9702b6-1837-4a5a-8b15-3d10b597a02a>

**Comment by jmpessoa** [comment]
Hello, Marcos!

Try each component separately..... and let me know if it works.....

(the fact is that both components use the same libraries with different versions...)
