### ISSUE TITLE
KToyButton não está gerando o build.gradle

### ISSUE THREAD

**Issue by marcos-ebm** [jmpessoa/lazandroidmodulewizard#507]
Olá Marques

ao colocar o **KToyButton** no form e build, está gerando um erro,  .......... indo atrás desse erro, vi que o **build.gradle** não está sendo gerado para poder rodar o kotlin

o build.gradle gerado, me parece que é o padrao para qualquer projeto, 

fuçando no arquivo **androidwizard_intf.pas** reparei que é nele onde é gerado o **build.gradle** certo??

nesse arquivo, vc colocou um BOOLEANO para se caso o Kotlin for usado, ele se tornara TRUE (FIsKotlinSupported: boolean;)

mas me parece que ele nao está sendo setado como TRUE ao colocar o KToyButton no form

minha pergunta para poder tentar ajudar a achar o erro é ...........Ao Colocar o KToy no form, quem cria e chama o TAndroidProjectDescriptor ??

fora isso, o BUILD.GRADLE, do programa demo AppCompatKToyButtonDemo1 está faltando coisas ........Mas isso é para outra hora

**Comment by jmpessoa** [comment]
Hello, Marcos!

 KToyButton is just a "concept proof"   It's not ready for use....

Yes, we can make it work but it won't change the reality of things.... 
for now we don't have the time to port LAMW from java to kotlin....

**Comment by jmpessoa** [comment]
"androidwizard_intf.pas" is called to create/configure a new project.... then when re-opening a project the "smartdesigner.pas"
is responsible for project updates....

**Comment by jmpessoa** [comment]
Ok.  I will try fix it....  another alternative is drop it from IDE tab...
