### ISSUE TITLE
jView - cannot find symbol

### ISSUE THREAD

**Issue by marcos-ebm** [jmpessoa/lazandroidmodulewizard#513]
[Using the translator]

Error compiling with jView component

cannot find symbol
18: private jCanvas jcanvas = null;
71: jcanvas = (jCanvas)canvas;

![Captura de Tela 2024-01-22 às 11 13 45](https://github.com/jmpessoa/lazandroidmodulewizard/assets/77758127/5e1ea574-8aa9-4d26-bd98-282c86c93d64)

**Comment by jmpessoa** [comment]
Fixed!

Thank you!
