### ISSUE TITLE
jcQRGen - checkDebugDuplicateClasses

### ISSUE THREAD

**Issue by marcos-ebm** [jmpessoa/lazandroidmodulewizard#515]
[using the translator]

When compiling the jcQRGen component with the Barcodegen component, it is giving a duplicate class error (see image)

If you put **configuration { }** inside **Android { }** (according to the image) the problem disappears, but I don't see any way to add this code

Is there any way to do this without messing with the smartdesigner.pas structure?

It would be interesting to add the code when using QRGen

```
configurations {
    all*.exclude group: 'com.google.zxing'
}
```

![erro](https://github.com/jmpessoa/lazandroidmodulewizard/assets/77758127/b84bf8f7-9382-424e-a790-77e38c13f8d0)

![acerto](https://github.com/jmpessoa/lazandroidmodulewizard/assets/77758127/734b51a8-32f4-4ca0-97e5-a9476ed07a72)

**Comment by jmpessoa** [comment]
Fixed!

Thank you!
