### ISSUE TITLE
Why demos/*/bin folders are not cleaned?

### ISSUE THREAD

**Issue by odisey1245** [jmpessoa/lazandroidmodulewizard#9]

**Comment by jmpessoa** [comment]
Ok, I think that we need only de *.apk, sure?

**Comment by odisey1245** [comment]
Indeed, "apk" can be built from sources, so it is redundant too. But we can leave them. In my opinion, the primary worth of demos are their sources.

**Comment by jmpessoa** [comment]
Ok,  we can leave only "apk".... someone may have the curiosity to install/run the application to get to know

**Comment by odisey1245** [comment]
Size of whole "LazarusAndroidModuleWizard":
uncleaned demos/bin: 128M
after leave only "apk": 95M
totally cleaned demos/bin: 75M
after removing .so from demos/libs: 29M

**Comment by jmpessoa** [comment]
Can we cleanup /bin and  /libs [.so ] leaving just the source code and Apk?

**Comment by odisey1245** [comment]
Vote for, resulting size will be approx. 50M that is 2.5 times less.

**Comment by jmpessoa** [comment]
Ok [solved!] then we can close this issues!

**Comment by odisey1245** [comment]
We will close this issue when clean operation is finished.

**Comment by jmpessoa** [comment]
Ok.

**Comment by jmpessoa** [comment]
Anton, do you have all demos cleanup? If yes, can you do cleanup operation?

**Comment by odisey1245** [comment]
Ok, I'll do it.
