### ISSUE TITLE
Project Options / Application / Title is disabled !

### ISSUE THREAD

**Issue by freris** [jmpessoa/lazandroidmodulewizard#96]
Hi !  In New release of LAMW  the "Title" EditBox is disabled.  Please change in androidprojoptions.lfm  and in line 286 in component "object edLabel: TEdit", the enabled property from False to True.

      object edLabel: TEdit
        AnchorSideLeft.Control = cbTheme
        AnchorSideTop.Control = tsAppl
        Left = 59
        Height = 28
        Top = 6
        Width = 350
        BorderSpacing.Top = 6
        Enabled = True <<---------------  Is False !
        TabOrder = 1
      end

Thank you and Best Regards - Freris

**Comment by jmpessoa** [comment]
Fixed!!!

Thank you!

**Comment by freris** [comment]
Thank you toο !!
