### ISSUE TITLE
jexpandableListview cannot be cleared in runtime

### ISSUE THREAD

**Issue by jjhofman** [jmpessoa/lazandroidmodulewizard#98]
the jExpandableListview cannot be cleared in runtime.
after .clear  nothing happens.

**Comment by jmpessoa** [comment]
Hi, jjHofman!

I will try some solution!

Thank you!

**Comment by jmpessoa** [comment]
Done!!

New methods:
 ClearChildren(1);  //ex. clear all Children from group 1
 ClearGroup(1);     //ex. clear the group 1
 Clear();   // clear all list...

**Comment by jjhofman** [comment]
thanks very mutch
it works fine now :-)
